# Generated by Django 2.1.2 on 2018-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaractTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('cd_utilizacao', models.CharField(choices=[(1, 'Livre'), (1, 'Tabela'), (2, 'Assunto')], max_length=30)),
                ('cd_info_obrigatoria', models.CharField(choices=[('N/A', 'Nenhuma'), ('N', 'Valor numérico'), ('A', 'Valor alfa'), ('D', 'Data')], max_length=20)),
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Características',
                'db_table': 'caract_tipo',
                'ordering': ['descricao'],
            },
        ),
    ]
