# Generated by Django 2.1.2 on 2018-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracttipo',
            old_name='cd_utilizacao',
            new_name='cd_tipo_utilizacao',
        ),
        migrations.AddField(
            model_name='caracttipo',
            name='cd_utilizado_em',
            field=models.CharField(default='TESTE', max_length=30),
            preserve_default=False,
        ),
    ]
