# Generated by Django 2.1.2 on 2018-12-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0002_auto_20181201_1535'),
        ('App_Pessoa', '0001_initial'),
        ('App_Evento', '0002_auto_20181125_0043'),
        ('caract', '0002_auto_20181201_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaractRel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
                ('us_cad', models.CharField(default='ROOT', max_length=30)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valor_alfa', models.CharField(blank=True, max_length=30, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Características Relacionadas',
                'db_table': 'caract_rel',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='caracttipo',
            name='cd_info_obrigatoria',
            field=models.CharField(choices=[('N/A', 'Nenhuma'), ('N', 'Valor numérico'), ('A', 'Valor alfa'), ('D', 'Data')], help_text='Informação que será exigida. Ex: valor, alfanumérico ou data.', max_length=20),
        ),
        migrations.AlterField(
            model_name='caracttipo',
            name='cd_tipo_utilizacao',
            field=models.CharField(choices=[('T', 'Tabela'), ('A', 'Assunto')], help_text='Como será utilizado. Ex: tabela, por assunto e etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='caracttipo',
            name='cd_utilizado_em',
            field=models.CharField(help_text='Onde está sendo utilizado. Ex: tabela evento, processo pagamento e etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='caractrel',
            name='fk_caract_tipo_id',
            field=models.ForeignKey(blank=True, db_column='fk_caract_tipo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='caract.CaractTipo'),
        ),
        migrations.AddField(
            model_name='caractrel',
            name='fk_conta_id',
            field=models.ForeignKey(blank=True, db_column='fk_conta_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Conta'),
        ),
        migrations.AddField(
            model_name='caractrel',
            name='fk_evento_id',
            field=models.ForeignKey(blank=True, db_column='fk_evento_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Evento.Evento'),
        ),
        migrations.AddField(
            model_name='caractrel',
            name='fk_evento_tipo_id',
            field=models.ForeignKey(blank=True, db_column='fk_evento_tipo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Evento.Evento_Tipo'),
        ),
        migrations.AddField(
            model_name='caractrel',
            name='fk_grupo_id',
            field=models.ForeignKey(blank=True, db_column='fk_grupo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Grupo'),
        ),
        migrations.AddField(
            model_name='caractrel',
            name='fk_pessoa_id',
            field=models.ForeignKey(blank=True, db_column='fk_pessoa_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa'),
        ),
        migrations.AddField(
            model_name='caractrel',
            name='fk_titulo_id',
            field=models.ForeignKey(blank=True, db_column='fk_titulo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Lancto'),
        ),
    ]
