# Generated by Django 2.1.2 on 2018-12-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caract', '0003_auto_20181204_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caractrel',
            name='fk_caract_tipo_id',
            field=models.ForeignKey(db_column='fk_caract_tipo_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='caract.CaractTipo'),
            preserve_default=False,
        ),
    ]
