# Generated by Django 2.1.2 on 2018-12-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CgRefCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rv_domain', models.CharField(help_text='Domínio a ser utilizado. Ex: tabela.coluna', max_length=100)),
                ('rv_low_value', models.CharField(help_text='Valor de relacionamento', max_length=240)),
                ('rv_high_value', models.CharField(help_text='Valor auxiliar de relacionamento', max_length=240)),
                ('rv_meaning', models.CharField(max_length=240)),
                ('rv_abbreviation', models.CharField(blank=True, max_length=240, null=True)),
                ('dt_cad', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Códigos do Sistema (CRC)',
                'db_table': 'cg_ref_codes',
                'ordering': ['rv_domain', 'rv_low_value'],
            },
        ),
    ]
