# Generated by Django 2.1.2 on 2018-11-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vl_alfa', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'ordering': ['vl_alfa'],
            },
        ),
        migrations.CreateModel(
            name='Contato_Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Contatos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.IntegerField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('obs', models.TextField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Endereco_Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Endereços',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cd_sit', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativado')], default=1)),
                ('dt_cad', models.DateField()),
                ('apelido', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('rg', models.CharField(blank=True, max_length=10, null=True)),
                ('obs', models.TextField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome', 'dt_cad'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa_Pessoa_Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_pessoa_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa')),
            ],
            options={
                'verbose_name_plural': 'Pessoa Tipos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa_Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Pessoas',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='pessoa_pessoa_tipo',
            name='fk_pessoa_tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa_Tipo'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='fk_endereco_tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Endereco_Tipo'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='fk_pessoa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa'),
        ),
        migrations.AddField(
            model_name='contato',
            name='fk_contato_tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Contato_Tipo'),
        ),
        migrations.AddField(
            model_name='contato',
            name='fk_pessoa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa'),
        ),
        migrations.AlterUniqueTogether(
            name='pessoa_pessoa_tipo',
            unique_together={('fk_pessoa_id', 'fk_pessoa_tipo_id')},
        ),
    ]
