# Generated by Django 2.1.2 on 2018-11-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Evento', '0004_teste'),
        ('App_Pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='fk_evento_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='App_Evento.Evento'),
            preserve_default=False,
        ),
    ]
