# Generated by Django 2.1.2 on 2018-11-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pessoa', '0002_endereco_fk_evento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='fk_evento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Evento.Evento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='fk_pessoa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa'),
        ),
    ]
