# Generated by Django 2.1.2 on 2018-11-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pessoa', '0005_auto_20181102_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa_pessoa_tipo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa_pessoa_tipo',
            name='fk_pessoa_tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa_Tipo'),
        ),
    ]
