# Generated by Django 2.1.2 on 2018-11-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('dt_evento', models.DateField()),
                ('dt_cad', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('parcelas', models.IntegerField(default=1)),
                ('dt_alt', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['dt_evento', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Evento_Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Eventos',
                'db_table': 'evento_tipo',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='EventoPessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_evento_id', models.ForeignKey(db_column='fk_evento_id', on_delete=django.db.models.deletion.PROTECT, to='App_Evento.Evento')),
            ],
            options={
                'db_table': 'evento_pessoa',
            },
        ),
    ]
