# Generated by Django 2.1.2 on 2018-11-01 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('dt_evento', models.DateField()),
                ('dt_cad', models.DateField()),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_ajustado', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('parcelas', models.IntegerField(default=1)),
                ('dt_alt', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['dt_evento', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Evento_Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Eventos',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='fk_evento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Evento.Evento_Tipo'),
        ),
    ]
