# Generated by Django 2.1.2 on 2018-11-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Pessoa', '0001_initial'),
        ('App_Evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopessoa',
            name='fk_pessoa_pessoa_tipo_id',
            field=models.ForeignKey(db_column='fk_pessoa_pessoa_tipo_id', on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa_Pessoa_Tipo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fk_evento_tipo_id',
            field=models.ForeignKey(db_column='fk_evento_tipo_id', on_delete=django.db.models.deletion.CASCADE, to='App_Evento.Evento_Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='eventopessoa',
            unique_together={('fk_evento_id', 'fk_pessoa_pessoa_tipo_id')},
        ),
    ]
