# Generated by Django 2.1.2 on 2018-11-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Evento', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
