# Generated by Django 2.1.2 on 2018-11-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Evento', '0004_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
