# Generated by Django 2.1.2 on 2018-11-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pessoa', '0003_auto_20181102_1504'),
        ('App_Evento', '0005_delete_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_evento_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Evento.Evento')),
                ('fk_pes_pes_tp_pessoa_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa')),
            ],
            options={
                'db_table': 'Evento_Pessoa',
            },
        ),
    ]
