# Generated by Django 2.1.2 on 2018-11-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Evento', '0006_eventopessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventopessoa',
            name='fk_pes_pes_tp_pessoa_id',
        ),
    ]
