# Generated by Django 2.1.2 on 2018-11-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pessoa', '0006_auto_20181102_1653'),
        ('App_Evento', '0007_remove_eventopessoa_fk_pes_pes_tp_pessoa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopessoa',
            name='fk_pessoa_pessoa_tipo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='App_Pessoa.Pessoa_Pessoa_Tipo'),
            preserve_default=False,
        ),
    ]
