# Generated by Django 2.1.2 on 2018-11-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pessoa', '0006_auto_20181102_1653'),
        ('App_Evento', '0008_eventopessoa_fk_pessoa_pessoa_tipo_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventopessoa',
            unique_together={('fk_evento_id', 'fk_pessoa_pessoa_tipo_id')},
        ),
    ]
