# Generated by Django 2.1.2 on 2018-11-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Evento', '0009_auto_20181103_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
