# Generated by Django 2.1.2 on 2018-11-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Evento', '0010_auto_20181106_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='valor_inicial',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='valor_ajustado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='valor_final',
        ),
    ]
