# Generated by Django 2.1.2 on 2018-11-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('dt_cad', models.DateField()),
                ('vl_atual', models.IntegerField()),
                ('cd_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Contas',
                'db_table': 'conta',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Conta_Grupo_Tipo_Pagto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_tipo', models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1)),
                ('cd_contabil', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('obs', models.TextField(blank=True, max_length=4000, null=True)),
                ('fk_conta_id', models.ForeignKey(db_column='fk_conta_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Conta')),
            ],
            options={
                'verbose_name_plural': 'Parametrização de Conta/Grupo/Tipo Pagto',
                'db_table': 'conta_grupo_tipo_pagto',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('cd_tipo', models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Lancto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('dt_cad', models.DateField()),
                ('dt_vencto', models.DateField()),
                ('dt_pgto', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cd_tipo', models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1)),
                ('parcela', models.IntegerField()),
                ('parcela_total', models.IntegerField()),
                ('dt_alt', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=2000, null=True)),
                ('fk_conta_id', models.ForeignKey(db_column='fk_conta_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Conta')),
                ('fk_evento_pessoa_id', models.ForeignKey(blank=True, db_column='fk_evento_pessoa_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Evento.EventoPessoa')),
                ('fk_grupo_id', models.ForeignKey(db_column='fk_grupo_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Lançamentos',
                'db_table': 'titulo',
                'ordering': ['dt_vencto', 'dt_cad'],
            },
        ),
        migrations.CreateModel(
            name='LanctoExtrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_cad', models.DateField()),
                ('valor_saldo_anterior', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_saldo_atualizado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fk_titulo_id', models.ForeignKey(db_column='fk_titulo_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Lancto')),
            ],
            options={
                'verbose_name_plural': 'Extrato da Conta',
                'db_table': 'titulo_extrato',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fk_grupo_id', models.ForeignKey(db_column='fk_grupo_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'orcamento',
            },
        ),
        migrations.CreateModel(
            name='TipoPagto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Pagamentos',
                'db_table': 'tipo_pagamento',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='lancto',
            name='fk_tipo_pagto_id',
            field=models.ForeignKey(db_column='fk_tipo_pagto_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.TipoPagto'),
        ),
        migrations.AddField(
            model_name='conta_grupo_tipo_pagto',
            name='fk_grupo_id',
            field=models.ForeignKey(db_column='fk_grupo_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Grupo'),
        ),
        migrations.AddField(
            model_name='conta_grupo_tipo_pagto',
            name='fk_tipo_pagto_id',
            field=models.ForeignKey(db_column='fk_tipo_pagto_id', on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.TipoPagto'),
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('fk_grupo_id', 'ano', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='conta_grupo_tipo_pagto',
            unique_together={('fk_conta_id', 'fk_grupo_id', 'fk_tipo_pagto_id')},
        ),
    ]
