# Generated by Django 2.1.2 on 2018-11-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('dt_cad', models.DateField()),
                ('vl_atual', models.IntegerField()),
                ('cd_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Contas',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Conta_Grupo_Tipo_Pagto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('cd_contabil', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('obs', models.TextField(blank=True, max_length=4000, null=True)),
                ('fk_conta_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Conta')),
            ],
            options={
                'verbose_name_plural': 'Parametrização de Conta/Grupo/Tipo Pagto',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('cd_tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Lancto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('dt_cad', models.DateField()),
                ('dt_vencto', models.DateField()),
                ('dt_pgto', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cd_tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('parcela', models.IntegerField()),
                ('parcela_total', models.IntegerField()),
                ('observacao', models.CharField(blank=True, max_length=2000, null=True)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Conta')),
                ('fk_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['dt_vencto', 'dt_cad'],
            },
        ),
        migrations.CreateModel(
            name='LanctoExtrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_cad', models.DateField()),
                ('valor_saldo_anterior', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_saldo_atualizado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fk_lancto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Lancto')),
            ],
            options={
                'verbose_name_plural': 'Extrato da Conta',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fk_grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Pagamentos',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='lancto',
            name='fk_tipo_pagto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.TipoPagto'),
        ),
        migrations.AddField(
            model_name='conta_grupo_tipo_pagto',
            name='fk_grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.Grupo'),
        ),
        migrations.AddField(
            model_name='conta_grupo_tipo_pagto',
            name='fk_tipo_pagto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Financeiro.TipoPagto'),
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('fk_grupo_id', 'ano', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='conta_grupo_tipo_pagto',
            unique_together={('fk_conta_id', 'fk_grupo_id', 'fk_tipo_pagto_id')},
        ),
    ]
