# Generated by Django 2.1.2 on 2018-12-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancto',
            options={'ordering': ['dt_vencto', 'dt_cad'], 'verbose_name_plural': 'títulos'},
        ),
    ]
