# Generated by Django 2.1.2 on 2018-11-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
