# Generated by Django 2.1.2 on 2018-11-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Evento', '0008_eventopessoa_fk_pessoa_pessoa_tipo_id'),
        ('App_Financeiro', '0002_delete_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancto',
            name='fk_evento_pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='App_Evento.EventoPessoa'),
            preserve_default=False,
        ),
    ]
