# Generated by Django 2.1.2 on 2018-11-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0003_lancto_fk_evento_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancto',
            name='fk_evento_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Evento.EventoPessoa'),
        ),
    ]
