# Generated by Django 2.1.2 on 2018-11-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0004_auto_20181102_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_grupo_tipo_pagto',
            name='cd_tipo',
            field=models.CharField(choices=[('D', 'Pagar'), ('C', 'Receber')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='cd_tipo',
            field=models.CharField(choices=[('D', 'Pagar'), ('C', 'Receber')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lancto',
            name='cd_tipo',
            field=models.CharField(choices=[('D', 'Pagar'), ('C', 'Receber')], max_length=1),
        ),
    ]
