# Generated by Django 2.1.2 on 2018-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0005_auto_20181111_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancto',
            name='dt_alt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
