# Generated by Django 2.1.2 on 2018-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0006_lancto_dt_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancto',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
