# Generated by Django 2.1.2 on 2018-11-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Financeiro', '0007_auto_20181111_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_grupo_tipo_pagto',
            name='cd_tipo',
            field=models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='cd_tipo',
            field=models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lancto',
            name='cd_tipo',
            field=models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1),
        ),
    ]
